title: xbzhao's Homepage
page-top-title: xbzhao
top-section-bg-text: University of Science and Technology Beijing
home-subtitle: xbzhao &ensp;|&ensp; 赵晓彬
copyright-text: '&copy; xbzhao 2025-2027. All Rights Reserved.'
